//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace educationn.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academics
    {
        public int ID_academics { get; set; }
        public string FIO { get; set; }
        public System.DateTime Date_Birth { get; set; }
        public string Specialization { get; set; }
        public int Date_assign_title { get; set; }
    }
}
