//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace educationn.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int Code_app { get; set; }
        public Nullable<int> Code_dic { get; set; }
        public string Number { get; set; }
    
        public virtual Discipline Discipline { get; set; }
    }
}
