//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace educationn.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exzamen
    {
        public int ID_exz { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Code_dic { get; set; }
        public Nullable<int> Reg_number { get; set; }
        public Nullable<int> Tab_number { get; set; }
        public string Auditoria { get; set; }
        public Nullable<int> Grade { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Student Student { get; set; }
    }
}
