//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace educationn.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UchebkaEntities : DbContext
    {
        public UchebkaEntities()
            : base("name=UchebkaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academics> Academics { get; set; }
        public virtual DbSet<Animal_Ziyatdinova> Animal_Ziyatdinova { get; set; }
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<Cafedra> Cafedra { get; set; }
        public virtual DbSet<Control_Ziyatdinova> Control_Ziyatdinova { get; set; }
        public virtual DbSet<Countries_Ziyatdinova> Countries_Ziyatdinova { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Discipline> Discipline { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Engineer> Engineer { get; set; }
        public virtual DbSet<Exzamen> Exzamen { get; set; }
        public virtual DbSet<Faculty> Faculty { get; set; }
        public virtual DbSet<Flowers_Ziyatdinova> Flowers_Ziyatdinova { get; set; }
        public virtual DbSet<Prepod> Prepod { get; set; }
        public virtual DbSet<Specialization> Specialization { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Ucheniki> Ucheniki { get; set; }
        public virtual DbSet<Zav_cafedra> Zav_cafedra { get; set; }
        public virtual DbSet<Licium> Licium { get; set; }
    }
}
