//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace educationn.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prepod
    {
        public int ID_prepod { get; set; }
        public Nullable<int> Tab_number { get; set; }
        public string Zvanie { get; set; }
        public string Stepen { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
